### ISSUE TITLE
Inference without MDX vocal separator

### ISSUE THREAD

**Issue by iruhamu03** [ardha27/AICoverGen-NoUI-Colab#7]
I've trying to inferencing my acapella using this notebook but the result are kinda terrible because of the MDX vocal separator
Is there's any way to directly inference my acapella to RVC without being processed by the MDX model?

**Comment by ardha27** [comment]
You can try to contact the owner of the code. Since i'm only cloning his code

**Comment by iruhamu03** [comment]
Ok, I'll ask it at his original repo

**Comment by iruhamu03** [comment]
Btw, kalo pake mode CLI kira-kira bisa gak langsung pake RVC tanpa MDX? Kalo bisa pake flags apa aja?
